// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinUITestProject.Infrastructure.Data;

#nullable disable

namespace WinUITestProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("WinUITestProject.Core.Entities.Folder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Parent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parent");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("folders");
                });

            modelBuilder.Entity("WinUITestProject.Core.Entities.FolderNote", b =>
                {
                    b.Property<int>("FolderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("folder_id");

                    b.Property<int>("NoteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FolderId", "NoteId");

                    b.HasIndex("NoteId");

                    b.ToTable("folder_notes");
                });

            modelBuilder.Entity("WinUITestProject.Core.Entities.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPinned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_pinned");

                    b.Property<int?>("TabOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tab_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("notes");
                });

            modelBuilder.Entity("WinUITestProject.Core.Entities.NoteTag", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tag_id");

                    b.Property<int>("NoteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TagId", "NoteId");

                    b.HasIndex("NoteId");

                    b.ToTable("note_tags");
                });

            modelBuilder.Entity("WinUITestProject.Core.Entities.Tag", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tags");
                });

            modelBuilder.Entity("WinUITestProject.Core.Entities.FolderNote", b =>
                {
                    b.HasOne("WinUITestProject.Core.Entities.Folder", "Folder")
                        .WithMany("FolderNotes")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WinUITestProject.Core.Entities.Note", "Note")
                        .WithMany("FolderNotes")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("WinUITestProject.Core.Entities.NoteTag", b =>
                {
                    b.HasOne("WinUITestProject.Core.Entities.Note", "Note")
                        .WithMany("NoteTags")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WinUITestProject.Core.Entities.Tag", "Tag")
                        .WithMany("NoteTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("WinUITestProject.Core.Entities.Folder", b =>
                {
                    b.Navigation("FolderNotes");
                });

            modelBuilder.Entity("WinUITestProject.Core.Entities.Note", b =>
                {
                    b.Navigation("FolderNotes");

                    b.Navigation("NoteTags");
                });

            modelBuilder.Entity("WinUITestProject.Core.Entities.Tag", b =>
                {
                    b.Navigation("NoteTags");
                });
#pragma warning restore 612, 618
        }
    }
}
